baseURL = "https://lokal.ninja/bremen"
languageCode = "de-DE"
title = "Bremen"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Lokal Ninja"
  org = "lokal-ninja"
  repo = "bremen"
